POST /api/stream HTTP/1.1
Host: localhost:5093
content-type: application/json
Content-Length: 87
Connection: keep-alive
Accept: */*

{
    "userPrompt": "Como Miguel cruzo la frontera entre Mexico y Estados Unidos"
}